name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/executive4.o:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/executive4.o:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/executive4.o:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/executive4.o:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/executive4.o:latest

  deploy:
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: Stop current service (mandatory downtime)
        run: |
          docker compose down

      - name: Pull latest image from Docker Hub
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/executive4.o:latest

      - name: Start service
        run: |
          docker compose up -d

      - name: Notify Slack of Deployment
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"✅ Deployment to VM with downtime completed successfully!"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
